# Generated by Django 5.2 on 2025-04-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_time', models.DateTimeField()),
                ('state', models.CharField(max_length=30)),
                ('delivery_guy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.deliveryguy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
